spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 77822
    username: root
    url: jdbc:mysql://localhost:3306/transportador
  jpa:
    hibernate:
      ddl-auto: update
    
